Enhance pogo cpp templates
tango-controls/TangoSourceDistribution pull request #16
Opened 2019-02-06 13:55 UTC by t-b

2019-03-29 14:36 UTC, bourtemb reviewed
Thanks @t-b for this useful Pull Request.
Let's take this opportunity to fix a few typos.

2019-03-29 14:36 UTC, bourtemb commented on assets/pogo/templates/cpp/Allowed.cpp
> +// description :  C++ source for the TemplateDevServ and its alowed.
Let's take this opportunity to fix some typos:
"alowed." => "allowed"

2019-03-29 14:36 UTC, bourtemb commented on assets/pogo/templates/cpp/Allowed.cpp
>  //                method for commands and attributes
method => methods

2019-03-29 14:36 UTC, bourtemb commented on assets/pogo/templates/cpp/MachineState.cpp
> +// description :  C++ source for the TemplateDevServ and its alowed
alowed => allowed

2019-03-29 14:52 UTC, t-b commented
@bourtemb Done.

2019-04-01 15:40 UTC, bourtemb requested changes
I tested the changes and tried to generate a device server source code using a POGO installed from this branch of the SourceDistribution.
I noticed that this new version of the templates didn't seem to be taken into account by POGO (still no trace of std::string in the generated code).
So I investigated a bit further and I discovered that these templates do not seem to be used any longer by POGO?
It looks like the templates which are used are the ones in https://github.com/tango-controls/pogo/tree/master/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/cpp
@Pascal-Verdier , could you confirm, please?

If it is confirmed these POGO templates from the source distribution are useless, we should remove them and update the POGO startup script which seems to define some variables to point to these templates.

We should also update the files in https://github.com/tango-controls/pogo/tree/master/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/cpp in the POGO git repository.

2019-04-02 08:26 UTC, bourtemb commented
I got confirmation from @Pascal-Verdier that these templates provided with the source distribution are now obsolete. They were used by Pogo 6. We should remove them from the Source distribution.
Now, the ones which are used are the ones in https://github.com/tango-controls/pogo/tree/master/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/cpp
So, a similar Pull Request should be proposed in [POGO Github repository](https://github.com/tango-controls/pogo).

2019-04-02 10:22 UTC, t-b commented
@bourtemb So the correct ones are https://github.com/tango-controls/pogo/tree/master/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/cpp?

2019-04-02 11:01 UTC, bourtemb commented
> 
> 
> @bourtemb So the correct ones are https://github.com/tango-controls/pogo/tree/master/fr.esrf.tango.generator.xtend/src/fr/esrf/tango/pogo/generator/cpp?

Yes

2019-04-02 13:14 UTC, t-b commented
@bourtemb Okay I'll create a new PR on the pogo repo. Can you then delete these old files here?

2019-04-02 13:14 UTC, closed without merging

2019-04-02 13:15 UTC, bourtemb commented
> @bourtemb Okay I'll create a new PR on the pogo repo. Can you then delete these old files here?

@t-b, thanks! Sure, I'll take care of removing these old files here.